apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: ghcr.io/eyalmor-ent/django:latest
          resources:
            limits:
              cpu: "1.0"
              memory: 500M
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
