apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  selector:
    matchLabels:
      name: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: # TBD
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
