apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: web-hpa
spec:
  scaleTargetRef:
    kind: Deployment
    name: web
  metrics:
    - type: Resource
  resource:
    name: cpu
    target:
      type: Utilization
      averageUtilization: 50
