apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kustomize-prod

commonLabels:
  env: dev

bases:
  - ../../base
  - namespace.yaml

patchesStrategicMerge:
  - deployment.yaml
  - hpa.yaml

