apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  env: staging
  namespace: kustomize-staging
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
